name: abc
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: 
  provider: 6.0.5
  math_expressions: <2.3.1
   # TOAST
  fluttertoast: 8.1.2

  # IMAGE
  cached_network_image: ">=3.2.3"

  # BASE
  intl: ">0.18.0"
  google_fonts: ^3.0.1
  html: ^0.15.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

dependency_overrides:
  flutter_lints: 1.0.1
  flutter_test: 1.1.1
